# This file was generated by GoReleaser. DO NOT EDIT.
cask "code-radar" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "b7e41e20e2d48603baf2b788d336718016a47cf68a15a855b56fa32899b9d064"
      url "https://github.com/iam-bkpl/code-radar/releases/download/v#{version}/code-radar_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b3a3a51d86f3c6987583aecad7eea7b33fdbb24671f699cecd734d0b1f3fa219"
      url "https://github.com/iam-bkpl/code-radar/releases/download/v#{version}/code-radar_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8eba93f84b1469132f59c4b2dbb50fe54f72730f7be5d7c9d0faad6f54ac1faa"
      url "https://github.com/iam-bkpl/code-radar/releases/download/v#{version}/code-radar_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6f3526d6db270dbcdfc027362b495ec1dcf758f76495e3d2c1dca0a50557c783"
      url "https://github.com/iam-bkpl/code-radar/releases/download/v#{version}/code-radar_Linux_arm64.tar.gz"
    end
  end

  name "code-radar"
  desc "Where is my code?"
  homepage "https://github.com/iam-bkpl/time-pugcha"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "code-radar"

  # No zap stanza required

end
