# This file was generated by GoReleaser. DO NOT EDIT.
cask "code-radar" do
  version "0.0.5"

  on_macos do
    on_intel do
      sha256 "c5958de2099919ea21ffc90be76a9d755d8398671c8f2523311a39319e091bd1"
      url "https://github.com/iam-bkpl/code-radar/releases/download/v#{version}/code-radar_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "aee5aadbf87fa5c8d0f2755f9c7cc10b607953a3a39f57bf4a9d56bbed0cb2af"
      url "https://github.com/iam-bkpl/code-radar/releases/download/v#{version}/code-radar_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "25f3440cc9f16f9af5930303e386e392237215cdc283474f859ad30416822e4c"
      url "https://github.com/iam-bkpl/code-radar/releases/download/v#{version}/code-radar_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d7d3ed6e1ef05d4148d252057bf33fead40f4259836c81da1c945e668fef5625"
      url "https://github.com/iam-bkpl/code-radar/releases/download/v#{version}/code-radar_Linux_arm64.tar.gz"
    end
  end

  name "code-radar"
  desc "Track where your git commits have been deployed across branches"
  homepage "https://github.com/iam-bkpl/code-radar"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "code-radar"

  # No zap stanza required

end
