# This file was generated by GoReleaser. DO NOT EDIT.
cask "code-radar" do
  version "0.0.3"

  on_macos do
    on_intel do
      sha256 "8a54bd270c9d629eb304a82303ce128121dfae58ed2f6ecf67e56fb1d2711a34"
      url "https://github.com/iam-bkpl/code-radar/releases/download/v#{version}/code-radar_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "7ca0ae7c18b3de0c999a18576f6b520f200a87157c16032216f98638cf95f35c"
      url "https://github.com/iam-bkpl/code-radar/releases/download/v#{version}/code-radar_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5b04bf4f635af2f52e04e56756375b05974bc718bb484566b05dba49285e50d4"
      url "https://github.com/iam-bkpl/code-radar/releases/download/v#{version}/code-radar_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f998349d763fdf706bb8a693169b6617ecd2cc8e1e6772530c0a1e51a55c6aab"
      url "https://github.com/iam-bkpl/code-radar/releases/download/v#{version}/code-radar_Linux_arm64.tar.gz"
    end
  end

  name "code-radar"
  desc "Track where your git commits have been deployed across branches"
  homepage "https://github.com/iam-bkpl/code-radar"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "code-radar"

  # No zap stanza required

end
