# This file was generated by GoReleaser. DO NOT EDIT.
cask "time-pugcha" do
  name "time-pugcha"
  desc "Can i have a coffee break ?"
  homepage "https://github.com/iam-bkpl/time-pugcha"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "time-pugcha"

  on_macos do
    on_intel do
      url "https://github.com/iam-bkpl/time-pugcha/releases/download/v#{version}/time-pugcha_Darwin_x86_64.tar.gz"
      sha256 "176eae2ed46b32489548f56a32bb0d5432e892aa2367a4ef3e51806d5f49e4df"
    end
    on_arm do
      url "https://github.com/iam-bkpl/time-pugcha/releases/download/v#{version}/time-pugcha_Darwin_arm64.tar.gz"
      sha256 "c5dd7ca0872df10aed1208f9089dcc5bde8c307bd6a2a8d6046b170d2a0cb99f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/iam-bkpl/time-pugcha/releases/download/v#{version}/time-pugcha_Linux_x86_64.tar.gz"
      sha256 "d2201111975745677d0449532728392d051c2d05a7d02e01bfa5cb0a771dadff"
    end
    on_arm do
      url "https://github.com/iam-bkpl/time-pugcha/releases/download/v#{version}/time-pugcha_Linux_arm64.tar.gz"
      sha256 "52df1e3528b51cb295c89ef3c0c2f0ee146e544b12039d634b3892e33c9247ac"
    end
  end

  # No zap stanza required
end
