# This file was generated by GoReleaser. DO NOT EDIT.
cask "time-pugcha" do
  name "time-pugcha"
  desc "Can i have a coffee break ?"
  homepage "https://github.com/iam-bkpl/time-pugcha"
  version "0.0.22"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "time-pugcha"

  on_macos do
    on_intel do
      url "https://github.com/iam-bkpl/time-pugcha/releases/download/v#{version}/time-pugcha_Darwin_x86_64.tar.gz"
      sha256 "332d2e33274ffacc5daafbf95e3ddad670e36c4aa8c5f403a6866bb3cdfe2c13"
    end
    on_arm do
      url "https://github.com/iam-bkpl/time-pugcha/releases/download/v#{version}/time-pugcha_Darwin_arm64.tar.gz"
      sha256 "66ea058f39cb0332d82364e11d9951938d812dfcd70edab1283de6863d13dcef"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/iam-bkpl/time-pugcha/releases/download/v#{version}/time-pugcha_Linux_x86_64.tar.gz"
      sha256 "69d24817cd565f25bf0071fc0995d7303ba4c4516c6a19b4f79ce32bb80cf373"
    end
    on_arm do
      url "https://github.com/iam-bkpl/time-pugcha/releases/download/v#{version}/time-pugcha_Linux_arm64.tar.gz"
      sha256 "8f8f5ea60202467e8427746461f6e9873f2eac6d441cdf2e6b47dfe3853c5756"
    end
  end

  # No zap stanza required
end
